baseURL = "https://danieldia-dev.github.io/" # Replace with your actual username if different
languageCode = "en-us"
title = "Daniel Dia's Website"

# Number of items per page for lists (blog, portfolio)
[pagination]
pagerSize = 6

# Enable PostCSS processing for Tailwind
[build]
[build.buildStats]
enable = true
[[build.cachebusters]]
source = 'assets/notwatching/hugo_stats\.json'
target = 'css'
[[build.cachebusters]]
source = '(postcss|tailwind)\.config\.js'
target = 'css'
[module]
[[module.mounts]]
source = 'assets'
target = 'assets'
[[module.mounts]]
disableWatch = true
source = 'hugo_stats.json'
target = 'assets/notwatching/hugo_stats.json'

[params]
AuthorName = "Daniel Dia"
tagline = "Computer & Communications Engineering and Mathematics student @AUB | Cryptography Enthusiast" # Update with your tagline
profilePic = "pfp_small_blurred.png"                                                    # Path relative to static folder, e.g., static/D2.png
goatcounter_code = "danieldia"

[markup.goldmark.renderer]
unsafe = true # Allows raw HTML in Markdown, if needed

[markup.highlight]
# See a complete list of styles here: https://xyproto.github.io/splash/docs/all.html
style = "catppuccin-latte"
codeFences = true
guessSyntax = true
noClasses = false

# Main navigation menu
[menu]
  [[menu.main]]
    name = "Homepage"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
  [[menu.main]]
    name = "Portfolio"
    url = "/portfolio/"
    weight = 30
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 40
  [[menu.main]]
    name = "Academia"
    url = "/academia/"
    weight = 50
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 60
